# Generated by Django 4.2.3 on 2023-07-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='assignment',
            field=models.TextField(blank=True, verbose_name='課題'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, verbose_name='詳細'),
        ),
    ]
