# Generated by Django 4.2.3 on 2024-01-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_assignment_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='assignment',
            field=models.TextField(blank=True, max_length=20, verbose_name='課題'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, max_length=20, verbose_name='詳細'),
        ),
    ]
